### PR TITLE
Gradle integration

### PR DESCRIPTION
**Pull request by kshchepanovskyi**
With Gradle integration, plugin development is a lot easier, especially for new users. Now you do not need to download and install IntelliJ IDEA & source, gradle plugin takes care of that.

In order to start development you need:
1. Clone this repository
2. Run `./gradlew runIdea` - it will download all needed dependencies (including IDEA), compile & run IDEA instance with Sample Plugin enabled.

Now this sample uses `antlr4-jetbrains-adapter` library deployed to https://bintray.com/antlr/maven

### CODE REVIEW

**Comment by parrt** [comment]
hi. looks cool. i hope to get back to the plugin soon and evaluate.

**Comment by kshchepanovskyi** [comment]
Please send me your account name for https://bintray.com/ - I will transfer ownership for "antlr" organization.

**Comment by bjansen** [comment]
Thanks for the contribution @kshchepanovskyi!

Unfortunately, there were quite a few conflicts and the code was based on a fork of https://github.com/antlr/antlr4-intellij-adaptor/ which has since been uploaded to Maven Central. 

I moved the code base to a Gradle build in https://github.com/antlr/jetbrains-plugin-sample/commit/0b8d515b5d38e4240d79d69a5e00c7ead0bf301a, so this PR is not necessary anymore. Thanks again!

**Comment by kshchepanovskyi** [comment]
@bjansen thanks for working on this project.
I have quite a lot of changes in my fork, it's used for https://plugins.jetbrains.com/plugin/8277-protobuf-support

I hope eventually I'll be able to reintegrate my changes to the mainline and use it for my plugin as well.

**Pull request closed without merging**
